# Generated by Django 2.2.6 on 2021-02-18 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('telemedicine_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedtime',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blockedtime',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='blockedtime',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
